name: Fetch data from virustotal
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * sun'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
    - name: Update repo
      run: git pull origin main
    - name: Run a one-line script
      run: nim -d:virusTotalKey="${{ secrets.VIRUSTOTALKEY }}" r fpfetch.nim
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Fetching latest data'
        add: '.'